### ISSUE TITLE
Bug: submitting tags and url

### ISSUE THREAD

**Issue by hackertron** [State-Channel-4/backend#31]
getting error in middleware/auth.ts . on etheres.transaction.from()
TypeError: Cannot read properties of undefined (reading 'Transaction')
    at verifySignedFunctionMessage (/Projects/channel4/match-making/src/middleware/auth.ts:48:27)

**Comment by hackertron** [comment]
Also affect submitting urls

**Comment by hackertron** [comment]
could the issue be related to https://github.com/State-Channel-4/backend/blob/main/src/abi.json#L138 

because in https://github.com/State-Channel-4/backend/blob/main/src/middleware/auth.ts#L49 we are only sending params but not the address ?  

I modified the imports too from 
```
import  ethers  from 'ethers';
```
to 
```
import { ethers } from 'ethers';
```
that fixed the above undefined issue . 

but getting error 
```
Error: no matching fragment (operation="fragment", info={ "args": [ "asd" ], "key": "createTagIfNotExists" }, code=UNSUPPORTED_OPERATION, version=6.8.0)
    at makeError (/home/nightmare/Projects/channel4/match-making/node_modules/.pnpm/ethers@6.8.0/node_modules/ethers/src.ts/utils/errors.ts:694:21)
    at assert (/home/nightmare/Projects/channel4/match-making/node_modules/.pnpm/ethers@6.8.0/node_modules/ethers/src.ts/utils/errors.ts:715:25)
    at getFragment (/home/nightmare/Projects/channel4/match-making/node_modules/.pnpm/ethers@6.8.0/node_modules/ethers/src.ts/contract/contract.ts:270:15)
    at AsyncFunction.populateTransaction (/home/nightmare/Projects/channel4/match-making/node_modules/.pnpm/ethers@6.8.0/node_modules/ethers/src.ts/contract/contract.ts:278:26)
    at verifySignedFunctionMessage (/home/nightmare/Projects/channel4/match-making/src/middleware/auth.ts:53:11)
    at Layer.handle [as handle_request] (/home/nightmare/Projects/channel4/match-making/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/layer.js:95:5)
    at Immediate.next (/home/nightmare/Projects/channel4/match-making/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:144:13)
    at processImmediate (node:internal/timers:476:21) {
  code: 'UNSUPPORTED_OPERATION',
  operation: 'fragment',
  info: { key: 'createTagIfNotExists', args: [ 'asd' ] },
  shortMessage: 'no matching fragment'
}
```

**Comment by hackertron** [comment]
https://github.com/ethers-io/ethers.js/issues/3809
